# Generated by Django 4.1.7 on 2023-07-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('enrolled_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization')),
            ],
        ),
    ]
